#!/usr/bin/env python

import argparse
import os

parser = argparse.ArgumentParser(description='Delete git branches on local and remote')
parser.add_argument('branch_name', help='Remove selected branch')
parser.add_argument('-f', help='Force deletion', action='store_true')
parser.add_argument('-r', '--remote', help='Specify remote branch', default='origin')
args = parser.parse_args()

delete_remote_command = 'git push --delete {} {}'.format(args.remote, args.branch_name)
delete_local_command = 'git branch -d {}'.format(args.branch_name)

if args.f:
    delete_local_command = 'git branch -D {}'.format(args.branch_name)

os.system(delete_remote_command)
os.system(delete_local_command)
